### ISSUE TITLE
Firefox display bug

### ISSUE THREAD

**Issue by GalaBiggs** [UAMediaProd/banner-tool#1]
Hi Hui, Just letting you know that the banner tool is a little buggy in Firefox and is displaying weirdly. Please see screen shot. @huiua 
![Screenshot_2022-04-04 Banner Tool](https://user-images.githubusercontent.com/102781382/161455054-514fff2b-18aa-4e1b-8d67-cf08e48d51ba.png)

**Comment by huiua** [comment]
@GalaBiggs Thanks for reporting this. 

Can you please let me know which Firefox version you are using and whether you are using macOS or Windows?

As I just checked the latest Firefox version on macOS is working ok on my end though.
<img width="658" alt="Screen Shot 2022-04-04 at 9 42 49 am" src="https://user-images.githubusercontent.com/101075316/161455370-a24271f9-3bca-4d15-8350-f9442b89db56.png">

<img width="1332" alt="image" src="https://user-images.githubusercontent.com/101075316/161455400-10a8142e-4e65-4735-99e1-56138ac9125f.png">

**Comment by GalaBiggs** [comment]
Hey @huiua thanks for getting back so quick on this :-)

I am using Windows 10 with Firefox version 79.

![image](https://user-images.githubusercontent.com/102781382/161473065-40c95aae-087c-47d2-aac2-ee205a94c5f8.png)

**Comment by huiua** [comment]
Thanks, @GalaBiggs. 

Looks like some previous Firefox versions and Safari don't fully support scaling clip-path (which is the main styling method we use for the dynamic shield area). Unfortunately, your current Firefox version might be a bit out of date. 

Are you able to update it to the latest or use Chrome by any chance?

**Comment by GalaBiggs** [comment]
Cheers @huiua It appears that updates are disabled by the system administrator. I will contact ITDS and get it updated. I looked at the release date and my version dates back to 2020 and I have only had my new PC just over a month!
You can mark this as resolved if you like.
